spring.application.name=recall

# Databse Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/recall
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Actuator Endpoints Configuration
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# JWT
jwt.secret=${JWT_SECRET}
